version: "3.9"

services:
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics is_running
      interval: 2s
      timeout: 5s

  executor:
    image: openjdk:11
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 1s
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure
    volumes:
      - "./files/executor.jar:/executor.jar"
      - "./files/prod.conf:/prod.conf"
    command: >
      java
      -Dconfig.file=/prod.conf
      -Xverify:none
      -jar /executor.jar
