version: "3.9"


services:
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672

  executor:
    image: openjdk:11
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 3s
    depends_on:
      - rabbitmq
    restart: on-failure
    volumes:
      - "../target/scala-2.12/StringHound_SliceExecutor-assembly-1.0.0.jar:/worker.jar"
      - "./init.sh:/init.sh"
      - "./prod.conf:/prod.conf"
    command: [ "/bin/sh", "/init.sh" ]

