version: "3.9"


services:
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672

  worker:
    image: openjdk:11
    deploy:
      replicas: 2
    depends_on:
      - rabbitmq
    volumes:
      - "../target/scala-2.12/StringHound_SliceExecutor-assembly-1.0.0.jar:/worker.jar"
      - "~/prod.properties:/prod.properties"
    command: ["java", "-Xverify:none", "-Dconfig.file=/prod.properties", "-jar", "/worker.jar"]