version: "3.9"

services:
  rabbitmq:
    container_name: rmq
    image: rabbitmq:3.10-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics is_running
      interval: 2s
      timeout: 5s
    restart: on-failure

  executor:
    #    image: ghcr.io/roxchgt/sth-executor:latest
    image: openjdk:11
    deploy:
      replicas: 8
      restart_policy:
        condition: always
        delay: 1s
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - "./files/executor.jar:/executor.jar"
      - "./files/prod.conf:/prod.conf"
    command: >
      java
      -Dconfig.file=/prod.conf
      -Xverify:none
      -jar /executor.jar
